name: CD
on: 
  workflow_dispatch:
  # push:
  #   branches:
  #     - "feature/*"

jobs: 
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Bump release version
        id: bump_version
        uses: christian-draeger/increment-semantic-version@1.0.3
        with:
          current-version: '2.11.7'
          version-fragment: 'rc'

      - name: Do something with your bumped release version
        run: echo ${{ steps.bump_version.outputs.next-version }}

  build1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Process version of the tag
      id: version
      uses: ncipollo/semantic-version-action@v1
    - name: Dump steps context
      env:
        STEPS_CONTEXT: ${{ toJson(steps.version.outputs) }}
      run: echo "$STEPS_CONTEXT"
    - name: Dump previous tag
      env:
        PREVIOUS_TAG: ${{ steps.version.outputs.previous_tag }}
      run: echo "$PREVIOUS_TAG"



  #     - name: build image and push to docker hub
  #       uses: docker/build-push-action@v1.1.0
  #       with:
  #         username: ${{ secrets. DOCKER_USER }}
  #         password: ${{ secrets. DOCKER_PASSWORD }}
  #         repository: csturion/go-app
  #         tags: ${{ github.sha }}, latest

  # deploy: 
  #   name: Deploy
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3

  #     - name: kustomize
  #       uses: imranismail/setuo-kustomize@v1
  #       with: 
  #         kustomize_version: v3.6.1

  #     - name: update k8s
  #       run: |
  #         cd k8s
  #         kustomize edit set image go-app=csturion/go-app:${{ github.sha }}
  #         cat kustomization.yaml

  #     - name: commit
  #       run: |
  #         git config --local user.email "action@github.com"
  #         git config --local user.name "Deploy Action"
  #         git commit -am "change image tag"

  #     - name: push
  #       uses: ad-m/github-push-action@master
          